# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-28082281-1'

menu:
- {name: 'About', path: 'navigation', url: 'about/'}
- {name: 'Tags', path: 'navigation', url: 'tags/'}
- {name: 'Projects', path: 'navigation', url: 'projects-and-series/'}
- {name: 'Now', path: 'navigation', url: 'now/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/harveynick'}
- {icon: 'twitter', link: 'https://twitter.com/harveynick'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'rss-square', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_tags: 'Tagged with'

sharing_button_prompt: 'Share:'

hacker_news_prompt: 'Discuss this post on Hacker News'

post_date_prefix: 'Written on'

post_navigation:
  # Options are 'category', and 'site'. 'category' will only used the first
  # category assigned to the post.
  type: category

  # Available positions are 'top', and 'bottom'.
  postion: []

  previous_title: 'Previous post'

  next_title: 'Next post'

related_posts:

  category_toc_heading: '{category}'

  # Text for heading above related posts.
  heading: 'Related Posts:'

  # Method used to generate related posts. Options are:
  # 'tags' - Related posts are randomly selected from those with shared tags.
  # 'site' - Related posts are randomly selected from the contents of
  #          `site.related_posts`.
  type: site

  # Enable to declare a post field (declared in the post front matter) which
  # should be used as a filter for which posts are included in the related posts.
  # post_filter: favourite

  # Maximum number of related posts to show below each post.
  count: 3

  # Whether the content of the post_navigation should be excluded from the
  # related posts.
  exclude_post_navigation: true
